package com.astrawms.task.api;

import jakarta.validation.constraints.NotBlank;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public final class TaskDtos {

    private TaskDtos() {
    }

    /** RF confirmation: the operator scans the LPN, then the location label (location ID + check digit). */
    /**
     * RF putaway confirmation: the LPN, then the location label (ID + check digit). A location other than the suggested
     * one needs {@code overrideReason} (ADR-0021): LOCATION_FULL, LOCATION_BLOCKED, LOCATION_DAMAGED, CLOSER_LOCATION,
     * CONSOLIDATE, OTHER.
     */
    public record ConfirmRequest(@NotBlank String lpnId, @NotBlank String locationId, @NotBlank String checkDigit,
                                 String overrideReason) {
    }

    /** RF exception (PUT-EX-02 / PUT-EX-04): LOCATION_BLOCKED, LOCATION_OCCUPIED, LPN_NOT_FOUND. */
    public record ExceptionRequest(@NotBlank String reason, String detail) {
    }

    /** PICK fields ({@code allocationId} … {@code qtyPicked}) are null for PUTAWAY tasks. */
    public record TaskView(UUID id, String taskType, String status, int priority, String ownerId, String lpnId,
                           String fromLocation, String targetLocation, String strategy,
                           String exceptionReason, String assignedTo, String confirmedLocation,
                           UUID inventoryOperationId, List<Content> contents, Instant createdAt,
                           Instant completedAt, UUID allocationId, String orderRef, String orderLineRef,
                           String itemNo, String lotNo, BigDecimal qty, String uom, String toLpn,
                           BigDecimal qtyPicked, UUID countId, Integer countSequence, String suggestedLocation,
                           String receiveKind, String docNo, String partner, tools.jackson.databind.JsonNode expectedLines,
                           int scans, String overrideReason, String shortReason, String shortAction, Instant assignedAt) {
    }

    /** RF receiving scan; {@code scanId} is generated by the device per scan (a retry with it is harmless). */
    public record ReceiveRequest(@NotBlank String scanId, @NotBlank String docNo, @NotBlank String itemNo, String ownerId,
                                 @jakarta.validation.constraints.NotNull @jakarta.validation.constraints.Positive BigDecimal qty,
                                 @NotBlank String uom, String lotNo, java.time.LocalDate expiryDate, List<String> serials,
                                 String lpnId, @NotBlank String locationId, @NotBlank String checkDigit,
                                 String conditionGrade, String disposition, String returnReason, String overrideReason) {
    }

    /** RF finish of a receiving task; lines received short need a reason (SHORT_VENDOR, DAMAGED, REFUSED, IN_TRANSIT). */
    public record ReceiveCloseRequest(java.util.Map<String, String> shortReasons) {
    }

    /**
     * RF pick confirmation: the operator scans the source location label (check digit), picks {@code qty} (less than
     * requested = short pick, PCK-003) and scans serials for serial-tracked items.
     */
    /** A counted line on RF: what the counter finds, never compared on screen (blind count, INV-003). */
    public record CountedLine(@NotBlank String ownerId, @NotBlank String itemNo, String lotNo, String lpnId,
                              @jakarta.validation.constraints.NotNull @jakarta.validation.constraints.PositiveOrZero BigDecimal qty) {
    }

    /** RF count confirmation: the location's check digit and the lines found (empty = location empty). */
    public record CountConfirmRequest(@NotBlank String checkDigit, List<@jakarta.validation.Valid CountedLine> lines) {
    }

    /** RF replenishment confirmation: the check digit of the forward location the stock is dropped at. */
    public record ReplenConfirmRequest(@NotBlank String checkDigit) {
    }

    /** RF return confirmation: the check digit of the location the stock is put back to. */
    public record ReturnConfirmRequest(@NotBlank String checkDigit) {
    }

    /**
     * RF pick: source check digit, the scanned item (item number or GTIN, ADR-0020), the quantity and serials. Less than
     * requested needs {@code shortReason} (NOT_FOUND, DAMAGED, QTY_LESS, WRONG_ITEM, OTHER) and may choose
     * {@code shortAction}: REALLOCATE (default), BACKORDER or SHIP_SHORT.
     */
    public record PickConfirmRequest(@NotBlank String checkDigit, String item, @jakarta.validation.constraints.NotNull
                                     @jakarta.validation.constraints.PositiveOrZero BigDecimal qty, List<String> serials,
                                     String shortReason, String shortAction) {
    }

    public record Content(String ownerId, String itemNo, String lotNo, BigDecimal qty) {
    }
}
